### ISSUE TITLE
how to use?(dl-glasses-identifier)

### ISSUE THREAD

**Issue by dragonview** [dasec/glasses-detection#2]
Hi, How to run dl-glassess-identifier ?

**Comment by fstruck** [comment]
@dragonview Hi, after you have built the dl-glasses-identifier successfully, you can run the binary without any parameters which lists the provided parameters with a short description. There is a mistake in the description of the --input parameter (input file is an image or a text file with paths to images) which will be fixed.

As an example you can run following command:

_./glasses-identifier --model glasses-detection-v2-deploy.prototxt --train glasses-detection-v2-123_iter_100000.caffemodel --input image.png --mode scoring_

which calculates the features of the input image which can be used for glasses classification using a simple threshold.
